stages:
    - setup
    - test

setup:
    stage: setup
    script: bash .bootstrap.sh
    tags:
        - archlinux
docs:
    stage: test
    script:
      - source .venv/bin/activate
      - tox -e docs
    tags:
        - archlinux

syntax:
    stage: test
    script:
      - source .venv/bin/activate
      - tox -e syntax
    tags:
        - archlinux

py37:
    stage: test
    script:
      - source .venv/bin/activate
      - tox -e py37
    tags:
        - archlinux
