stages:
    - setup
    - test

setup:
    stage: setup
    script: bash .bootstrap.sh
    tags:
        - archlinux
docs:
    stage: test
    script: tox -e docs
    tags:
        - archlinux

syntax:
    stage: test
    script: tox -e syntax
    tags:
        - archlinux

py37:
    stage: test
    script: tox -e py37
    tags:
        - archlinux
