stages:
    - setup
    - test

setup:
    stage: setup
    script: bash .bootstrap.sh
    artifacts:
      paths:
        - .tox
        - .venv
    tags:
        - archlinux
docs:
    stage: test
    dependencies:
      - setup
    script:
      - source .venv/bin/activate
      - tox -e docs
    tags:
        - archlinux

syntax:
    stage: test
    dependencies:
      - setup
    script:
      - source .venv/bin/activate
      - tox -e syntax
    tags:
        - archlinux

py37:
    stage: test
    dependencies:
      - setup
    script:
      - source .venv/bin/activate
      - tox -e py37
    tags:
        - archlinux
